# Generated by Django 5.1.7 on 2025-03-12 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("vivienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="tipo_habitante",
            field=models.CharField(
                blank=True,
                choices=[
                    ("titular", "Titular"),
                    ("dueno", "Dueño"),
                    ("copropietario", "Copropietario"),
                    ("menor", "Menor"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="vivienda",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="residentes",
                to="vivienda.vivienda",
            ),
        ),
    ]
