databases:
  - name: condoforgedb
    plan: free
    databaseName: condoforge
    user: condoforge

services:
  - type: web
    plan: free
    name: condoforge
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: condoforge
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4