# Generated by Django 5.1.7 on 2025-03-12 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("Perro", "Perro"),
                            ("Gato", "Gato"),
                            ("Otro", "Otro"),
                        ],
                        max_length=30,
                    ),
                ),
                ("raza", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="mascotas/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vivienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                (
                    "habitantes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="habitantes_vivienda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mascotas",
                    models.ManyToManyField(
                        blank=True,
                        related_name="viviendas_asociadas",
                        to="vivienda.mascota",
                    ),
                ),
                (
                    "titular",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="titular_vivienda",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="mascota",
            name="vivienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mascotas_vivienda",
                to="vivienda.vivienda",
            ),
        ),
    ]
